server:
  port: 8080
  servlet:
    session:
      persistent: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  mail:
    host: smtp.gmail.com
    port: 587
    username: "huynhphat1122003@gmail.com"
    password: "vsgpwbfodmvcxncz"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  docker:
    compose:
      enabled: false
  http:
    encoding:
      enabled: true
      charset: UTF-8
api:
  prefix: api/v1
jwt:
  expiration: 1800 #30minutes = 30 * 60
  secretKey: Z7hjrPTXlc9XLzJCO7kyYZWh1DiskWLbplYzgBHIREU=
  refresh-expiration: 604800 #7days = 7 * 24 * 60 * 60
springdoc:
  api-docs:
    path: /apidocs
  swagger-ui:
    path: /apidocs.html

open:
  api:
    title: API Documents
    version: v1.0.0
    description: Nothing special
    serverUrl: http://localhost:8080/
    serverName: Server test
resource:
  noImageUrl: "https://res.cloudinary.com/drgidfvnd/image/upload/v1713243712/no-image.1024x1024_gyl3zk.png"

